### PR TITLE
Added emacs25 compatibility.

### PR DESCRIPTION
**Pull request by pdo**
Now works in Emacs 25 as well as 24.

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks for this. If I remember correctly, then I added this here because the upstream repository had disappeared, so it is correct to open this issue here. But it cannot hurt to double check - did you try to contact the author? I think the best outcome would be if this were added to Emacs itself, though I don't know if the code is in a good enough state. Could you please talk to the author about this?

Concerning merging this here: I don't think maintaining compatibility with Emacs v24 is worth the complications. Please drop that and only support >= v25.

**Comment by pdo** [comment]
Hi Jonas,

Sorry for the delayed response.  I have been in communication with the
author and he has created a github mirror of his project at
venks1/emacs-fossil to which we will be redirecting MELPA shortly.  We are
working on some updates to the code right now, and maintaining v24
compatibility as it is important to the author.

I'll post another message here when I think it's safe to delete the
emacsorphanage/vc-fossil repository.

Thanks for your help,
Paul

**Comment by tarsius** [comment]
Great! Thanks!

**Comment by tarsius** [comment]
I have moved this repository to my personal account and will soon delete it.

**Pull request closed without merging**
